### ISSUE TITLE
Todos?

### ISSUE THREAD

**Issue by schteppe** [flyover/box2d.ts#1]
How much of box2d is ported and how much is left to do? Is there a todo list or maybe stubs in the code? It would be really nice to have a todo list, to be able to continue working on the project and to compare to other ports (there are already too many, of varying completeness and quality).

Really like what you have done this far. Is this a manual port? Maybe semi-automatic?

**Comment by flyover** [comment]
Thanks for the feedback.  This is based on the [JavaScript](https://github.com/flyover/box2d.js) port, which is a manual port from Box2D.  All the basic functionality of the original Box2D is complete, minus any changes from recent commits in the last year or so.  I have yet to add Google's LiquidFun to this, as I have in the JavaScript port.

**Comment by schteppe** [comment]
Right... so what does "basic functionality" mean, specifically?

**Comment by flyover** [comment]
Everything from the original Box2D project.

**Comment by schteppe** [comment]
That's awesome! Thanks.
