### ISSUE TITLE
LICENSE Needed !

### ISSUE THREAD

**Issue by Nek-** [flyover/box2d.ts#14]
Hello,

I figure out that even if this project is open source, you didn't put any license. Also as there is already many contributors it's already a problem.

Contributors have rights on license choice. So I recommend you to add one ASAP.

Notice that I'm in favor of MIT :).

@finscn also need to give his though on this

**Comment by flyover** [comment]
Thanks for pointing this out.  I left the license the same as in the original Box2D source files.  I also added the LICENSE file and changed the entry in package.json.

**Comment by Nek-** [comment]
Thanks!
