### ISSUE TITLE
There are 2 local vars never been used.

### ISSUE THREAD

**Issue by finscn** [flyover/box2d.ts#15]
https://github.com/flyover/box2d.ts/blob/0277e6b8f678f3884c18d2dae0cd0596b6dfc043/Box2D/Box2D/Dynamics/Joints/b2DistanceJoint.ts#L307

qA & qB have never been used.

**Comment by flyover** [comment]
It was using the class members instead of the variables.  Fixed in 093c9cd9ab9e8dbe50140c949708f6740e8af1dc.

**Comment by finscn** [comment]
I advice that  add  `"noUnusedLocals": true,` to tsconfig , it could help you to find out some issues like this one.

**Comment by flyover** [comment]
Thanks for the advice.  I will do this.

**Comment by Nek-** [comment]
Guys, this issue can be close :) .
