### ISSUE TITLE
gravity should not be readonly

### ISSUE THREAD

**Issue by Nek-** [flyover/box2d.ts#18]
Last code update adds many variables as readonly https://github.com/flyover/box2d.ts/commit/1a109d97f72bdd0d10a6c1a79974fcc0c5af32b7#diff-7bf07a23ea2bae669d941930fde7633eR78

I think it's wrong. There should be a way to set the gravity (and others).

**Comment by flyover** [comment]
You should use the methods for this (b2World::Set/GetGravity, b2Body::Set/GetPosition, etc).

**Comment by Nek-** [comment]
My bad, I misread the original API !!
