### ISSUE TITLE
error

### ISSUE THREAD

**Issue by korolariya** [flyover/box2d.ts#2]
TS4073: Parameter 'proxy' of public method from exported class has or is using private name 'b2DistanceProxy'.

**Comment by flyover** [comment]
What version of the Typescript compiler are you using?

**Comment by korolariya** [comment]
Version: webpack 2.3.0
Time: 5483ms
"ts-loader": "^2.0.3",
 "typescript": "^2.3.2"

**Comment by flyover** [comment]
I'm not seeing this error using the build setup in this project using tsc 2.3.2 or 2.3.4.  Is there a place where I can find your setup that is using the webpack loader?

**Comment by korolariya** [comment]
Here https://github.com/likemyjob/PixiProjectArcanoid

**Comment by flyover** [comment]
Thanks.
Fixed in 240c4e42ae77cc716c30eb4a834259da8f025c39.
