### ISSUE TITLE
Some errors when build

### ISSUE THREAD

**Issue by finscn** [flyover/box2d.ts#23]
```
Collision/Shapes/b2Shape.ts(19,31): error TS6133: 'XY' is declared but its value is never read.
Common/b2Draw.ts(19,10): error TS6133: 'b2Vec2' is declared but its value is never read.
Dynamics/b2Fixture.ts(20,31): error TS6133: 'XY' is declared but its value is never read.
```

**Comment by Nek-** [comment]
How do you build the project? Did you upgrade typescript? I don't have these issues.

**Comment by finscn** [comment]
add `"noUnusedLocals": true,` into tsconfig.json

**Comment by flyover** [comment]
I have a branch ready that enables all the strict and noImplicit options and fixes the errors.  It also contains fixes for most of the default tslint errors.  I should have it committed soon.

**Comment by flyover** [comment]
I think this is fixed now.  Let me know if otherwise.
