### ISSUE TITLE
How to build box2d.ts to one js file and use it in browser ?

### ISSUE THREAD

**Issue by finscn** [flyover/box2d.ts#25]
as title said.

**Comment by Nek-** [comment]
A build is available in the folder Box2D/Build. It was originally generated by the Makefile. There's a probability that the makefile still work for some use cases, but as my PR suggest here: https://github.com/flyover/box2d.ts/pull/21/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15

Using the makefile is not the recommended way to build anymore. I'm working [on an improvement](https://github.com/Nek-/box2d.ts/commit/3006b78313db28fa8f99e68e45faf0de02202cf5) of the `package.json` configuration that will generate the file you want and also make the whole project easy to use with any TypeScript project.

**Comment by Nek-** [comment]
Btw I think the best approach is to have a "build" folder in the main directory which is not versioned and contains:

- All definition sources `"declaration": true`
- All files compiled to JS `"outDir": "dist"`
- A single file that contains all the code `"outFile": "dist/box2d-ts.js"`
- Maybe some other files in other format

**Comment by finscn** [comment]
with the last version of box2d, I know how to do it . thanks.
