### ISSUE TITLE
[RFC] Build configuration

### ISSUE THREAD

**Issue by Nek-** [flyover/box2d.ts#34]
Hello,

Opening PRs about build configuration leads to conflicts, hard rebases and then be forgotten... I think it's a good idea to discuss about the build policy.

Here is what I recommend. Please comment if you disagree with args about so I can understand and maybe suggest something else:

1. Change the build of the Testbed
    - Build in a separated folder `Box2D/Testbed/dist`
    - With webpack
    - Drop systemjs
    - Use the package instead of the code of Box2D available in the same repository directly
    - Means having its own `package.json` file (as well as `tsconfig.json`, so it makes sense)
2. Remove js files everywhere
    - There is so many files in the code base; research is a mess because of duplication in folders
    - Presence of JS files above the TS one make no sense
3. Build Box2D.js with `module: es2015` / `moduleResolution: node`
    - This is the most used configuration
    - With `declarations: true` and specify declaration as `typings`
    - The folder will be `dist/Box2D`
4. Build a single file with webpack concat or the configuration of `tsconf.json` if possible
    - Located in `dist/Box2D.dev.js`
    - And `dist/Box2D.min.js`

Please give feedbacks on these points.

Please notice that for the moment I use a custom configuration because your package does not work for me. Here is my branch with this config: https://github.com/Nek-/box2d.ts/tree/feature/many-output

**Comment by flyover** [comment]
Do you have a branch with the Testbed building with webpack?

**Comment by Nek-** [comment]
Here is some work, but nothing definitive ATM https://github.com/Nek-/box2d.ts/tree/feature/new-build-system
