### ISSUE TITLE
What's the difference from your box2d.js (except language) 

### ISSUE THREAD

**Issue by finscn** [flyover/box2d.ts#4]
I mean the  difference about 
features
bugs
performance

And in the future ,  will you update this project only (give up box2d.js) ? 

thanks.

**Comment by flyover** [comment]
I still need to port some of the testbed tests for this project.  Other than that, the features are the same.  The performance is about the same for this and the JS project.  Eventually, I'll probably archive the JS project and replace it with a build of this project.

**Comment by finscn** [comment]
I created a benchmark case : 

http://fatidol.com/phy-benchmark/

the box2d.ts is the fast one !

**Comment by Nek-** [comment]
This looks awesome.

Do you plan to release and maintain this project?

**Comment by 2youyou2** [comment]
@finscn Could you also test this box2d js lib in your benchmark?

https://github.com/2youyou2/jsbox2d forked from https://code.google.com/archive/p/jsbox2d/

**Comment by finscn** [comment]
@2youyou2  , jsbox2d is an inactive project. 
Sorry,  I don't want to spend time on a dead "Girl" , even though  she is a beauty.
