### ISSUE TITLE
Hi, why there is no b2wheeljoint in this version of box2d?

### ISSUE THREAD

**Issue by badboy-tian** [flyover/box2d.ts#40]
b2WheelJoint

**Comment by Nek-** [comment]
Hello, thanks for reporting this issue.

But I believe you're wrong on this postulate. Here it is: https://github.com/flyover/box2d.ts/blob/master/Box2D/Dynamics/Joints/b2WheelJoint.ts

And also the car test: https://github.com/flyover/box2d.ts/blob/master/Testbed/Tests/Car.ts
