### ISSUE TITLE
Source code can't be compiled.

### ISSUE THREAD

**Issue by jcyuan** [flyover/box2d.ts#43]
![image](https://user-images.githubusercontent.com/850854/46915641-95f0a480-cfe0-11e8-8f2c-adef9c1403a3.png)

`function default_compare<T>(a: T, b: T): boolean { return a < b; }`

the error is 

> [ts]
cant assign “(a: A, b: B) => boolean” to “<T>(a: T, b: T) => boolean”
  arg “b” is not compatible with “b”
    cant assign “B” to type “A”

**Comment by jcyuan** [comment]
ts version 3.1.1

**Comment by flyover** [comment]
a8fab993e18a2b4ff5e547e0da5928a2fbd521ff
