### ISSUE TITLE
about pre-build definitions

### ISSUE THREAD

**Issue by jcyuan** [flyover/box2d.ts#53]
`// #if B2_ENABLE_PARTICLE`

is there some options in Rollup or somewhere to make this take effect?
for example `defines: { B2_ENABLE_PARTICLE: false }`
then the code in this section will be ignored when compiling?

thanks.

**Comment by flyover** [comment]
I agree this would be a nice feature.  As of now, these are just placeholders in the code.

**Comment by jcyuan** [comment]
@flyover what tool are you using for replacing those placeholders?

**Comment by flyover** [comment]
I had been just manually searching and commenting out the sections.  However, it looks like there is now something available for webpack.  https://github.com/nippur72/ifdef-loader

**Comment by jcyuan** [comment]
got it, thanks~
