### ISSUE TITLE
sleeping bodies wake on aabb collision

### ISSUE THREAD

**Issue by mafsays** [flyover/box2d.ts#59]
sleeping bodies wake up when their bounding box collides with another fixture's bounding box, rather than on the actual fixture shapes colliding - is this intentional? (it's not consistent with the behaviour of the flash version of box2d I am porting a game from)

**Comment by flyover** [comment]
It should behave the same way as the original C++ Box2D library.  Have you tested this there?

**Comment by mafsays** [comment]
ok - having spoken to someone with experience of the c++ version it seems this is expected behaviour, so not an issue, at least not for anyone apart from me ; )
