### ISSUE TITLE
The performance drops to 20+fps again. (since commit a65d936)

### ISSUE THREAD

**Issue by jcyuan** [flyover/box2d.ts#60]
today I just pulled the newest code from commit 'a65d936', and used the benchmark made by @finscn before http://fatidol.com/phy-benchmark/box2d-ts-test.html to test the performance.

the result is, the FPS drops to 20+ fps again.

also I have recorded 2 profiles to analyze the difference, I found that the new version made a big GC in the `b2WorldManifold::Initialize` function:

![image](https://user-images.githubusercontent.com/850854/58784307-ad36dd80-8615-11e9-8e0d-9b5a827d17e9.png)
(gc)

![image](https://user-images.githubusercontent.com/850854/58784440-0141c200-8616-11e9-9720-304400c6b327.png)
(no gc: old version)

**Comment by jcyuan** [comment]
also, could you please publish a release once a version is stable? thank you so much.

**Comment by Fxlr8** [comment]
@jcyuan what is the last stable commit that can be used?

**Comment by jcyuan** [comment]
> @jcyuan what is the last stable commit that can be used?

hmmm, i'm so sorry, missed this somehow and just found while tidying my issue list up...

you can try this: https://github.com/flyover/box2d.ts/issues/74#issuecomment-717122457

thanks.
