### ISSUE TITLE
Could someone publish a new npm package from the current version of the project?

### ISSUE THREAD

**Issue by Hyperkettu** [flyover/box2d.ts#61]
Could someone publish a new npm package from the current version. The current npm package appears to be broken since when I try to compile my project that uses box2d.ts npm package I get a type error in b2ParticleSystem.ts in function `std_lower_bound<A, B>(array: A[], first: number, last: number, val: B, cmp: (a: A, b: B) => boolean = default_compare)` where the error is probably caused because default_compare cannot be assigned to type `(a:A, b: B) => boolean` since it is of type `<T> (a: T, b: T) => boolean`. In the current version this seems to be fixed.

Thanks in advance.

**Comment by Fxlr8** [comment]
@flyover, do you need any help with that? The lib looks a little untidy now. I can help to set up the build pipeline and npm releases. This can really help to make this lib more popular. It deserves it!

**Comment by mobileben** [comment]
Just curious as I haven't seen much dialog in a bit. Is the current version avail (1.0.0) npm considered stable and one of the "faster" variants. I noticed #60 indicated slow performance.

I built a prototype using the latest from Build/Box2d/box2d.umd.js. Not sure if using the npm version has pros or cons.

**Comment by flyover** [comment]
The change that caused the slow performance in some cases has been reverted.  I have also recently updated the npm package at @flyover/box2d.
