### ISSUE TITLE
This project dead?

### ISSUE THREAD

**Issue by mobileben** [flyover/box2d.ts#65]
I guess I'll ask the question since my last few posted questions have not gotten any responses.

**Comment by Fxlr8** [comment]
I want to ask the same question. @flyover didn't answer to my email. @finscn are you still using this engine?

Personally, I don't want this repo to die. I see a lot of work done here and my project was built on top of it. I emailed Isaac to offer my help with maintenance, but he didn't answer.

**Comment by flyover** [comment]
Maybe just hibernating...  :)
I'll see if I can get through some of the issues from @mobileben and others.
