### ISSUE TITLE
bug with newest version

### ISSUE THREAD

**Issue by jcyuan** [flyover/box2d.ts#73]
since commit a7b8ddf737b442c054acde1ece459c74f0ca6c2b

this is a v2.4.0 porting i think, what i found is, if a body only contains 1 fixture, and the fixture has 0 density, then:

~~1. it won't collide with other bodies! (what i tested is collide with b2EdgeShape, my ground is b2EdgeShape)~~
2. it does not have gravity, it floats in the air and the color of the shape is dark red.

**Comment by Fxlr8** [comment]
How do you expect a body with zero density (zero amount of mass per given volume) to be affected by gravity? A body like this has zero mass.

**Comment by jcyuan** [comment]
> How do you expect a body with zero density (zero amount of mass per given volume) to be affected by gravity? A body like this has zero mass.

lol, yes! so i think this is a bug in the older version.
