### ISSUE TITLE
Why use import *.js in *.ts files

### ISSUE THREAD

**Issue by SeaPlanet** [flyover/box2d.ts#76]
```ts
export * from "./common/b2_settings.js";
...
```
Well, I'm not too good at Typescript. What good does it do??

**Comment by Fxlr8** [comment]
It takes all the exports from `"./common/b2_settings.js"` file and re-exports them. I think this is an artifact from js to ts migration.

**Comment by SeaPlanet** [comment]
I prefer to use ts source code, It doesn't matter🥶🥶🥶
